//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HL7TestingApp.ReportsWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ReportWCF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportsWebService.IReports")]
    public interface IReports {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReports/GetReports", ReplyAction="http://tempuri.org/IReports/GetReportsResponse")]
        string GetReports(string PatientName, string AccessionNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReports/GetReports", ReplyAction="http://tempuri.org/IReports/GetReportsResponse")]
        System.Threading.Tasks.Task<string> GetReportsAsync(string PatientName, string AccessionNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReports/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IReports/GetDataUsingDataContractResponse")]
        HL7TestingApp.ReportsWebService.CompositeType GetDataUsingDataContract(HL7TestingApp.ReportsWebService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReports/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IReports/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<HL7TestingApp.ReportsWebService.CompositeType> GetDataUsingDataContractAsync(HL7TestingApp.ReportsWebService.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportsChannel : HL7TestingApp.ReportsWebService.IReports, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportsClient : System.ServiceModel.ClientBase<HL7TestingApp.ReportsWebService.IReports>, HL7TestingApp.ReportsWebService.IReports {
        
        public ReportsClient() {
        }
        
        public ReportsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetReports(string PatientName, string AccessionNumber) {
            return base.Channel.GetReports(PatientName, AccessionNumber);
        }
        
        public System.Threading.Tasks.Task<string> GetReportsAsync(string PatientName, string AccessionNumber) {
            return base.Channel.GetReportsAsync(PatientName, AccessionNumber);
        }
        
        public HL7TestingApp.ReportsWebService.CompositeType GetDataUsingDataContract(HL7TestingApp.ReportsWebService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<HL7TestingApp.ReportsWebService.CompositeType> GetDataUsingDataContractAsync(HL7TestingApp.ReportsWebService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
